language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30

jdk:
  - openjdk8

sudo: false

before_cache:
  - rm -rf $HOME/.m2/repository/io/michaelrocks/paranoid-
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - yes | sdkmanager "platforms;android-30"

install:
  - ./gradlew assemble publishToMavenLocal -Pbootstrap=true -Ppablo.signing.enabled=false --no-daemon --rerun-tasks

script:
  - ./gradlew check --no-daemon
