name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-large

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14.3'
        cache-cleanup: 'always'
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and publish to Maven Local
      run: ./gradlew build test publishToMavenLocal --parallel --configuration-cache

    - name: Build samples
      run: |
          cd samples
          ./gradlew :application:assembleRelease :application-global-obfuscate:assembleRelease :library:assembleRelease :library-may-obfuscate:assembleRelease :library-obfuscate:assembleRelease --parallel --configuration-cache

    - name: Build testApp release (verify ProGuard rules)
      run: |
          cd testApp
          ./gradlew assembleRelease --configuration-cache

    - name: Enable KVM group permissions
      run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

    - name: Run instrumented tests on managed device
      run: |
          cd testApp
          ./gradlew pixel8api35DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect --configuration-cache

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: testApp/build/reports/androidTests/
        retention-days: 7

    - name: Upload test APKs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-apks
        path: |
          testApp/build/outputs/apk/debug/*.apk
          testApp/build/outputs/apk/release/*.apk
        retention-days: 7
      
