name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21]
        target: [default]
        arch: [x86_64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Publish bootstrap artifacts
        run: ./gradlew assemble publishToMavenLocal -Pbootstrap=true -Ppablo.signing.enabled=false --no-daemon --rerun-tasks

        # Skip unit tests for now. Seems free build machines are too restricted to compile them.
        # - name: Run unit tests
        #   run: ./gradlew check --no-daemon

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: ./gradlew connectedCheck --no-daemon
