name: Maven

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-large
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.maven_pgp_signingPassword }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.maven_ossrhUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.maven_ossrhPassword }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
