name: Maven

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-large
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14.3'
          cache-cleanup: 'always'
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        
          
      - name: Build with Gradle
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.maven_pgp_signingPassword }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.maven_ossrhUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.maven_ossrhPassword }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
